[project]
name = "energy-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bokeh>=3.8.0",
    "folium>=0.20.0",
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "pyproj>=3.7.2",
    "pyqt6>=6.9.1",
]
